### ISSUE TITLE
Connects to M1, Fails to retrieve information

### ISSUE THREAD

**Issue by 2765827892** [paulw11/homebridge-elkm1#12] opened 2020-12-07 02:07 UTC
Hello,

I am running the following versions:
Homebridge: 1.1.6
Node.js: 14.15.0
Elk Plugin: 1.1.10

The module successfully connects to the panel, however it can't retrieve data or text descriptions.

[12/6/2020, 9:00:49 PM] [ElkM1] Initializing ElkM1 platform...
[12/6/2020, 9:00:49 PM] [ElkM1] Connecting to M1
[12/6/2020, 9:00:49 PM] [ElkM1] ***Connected***
[12/6/2020, 9:00:49 PM] [ElkM1] Requesting area description
[12/6/2020, 9:00:49 PM] [ElkM1] Area description:[object Object]
[12/6/2020, 9:00:49 PM] [ElkM1] Requesting zone descriptions
[12/6/2020, 9:00:49 PM] [ElkM1] Connection is not secure
[12/6/2020, 9:01:04 PM] [ElkM1] Error retrieving data from M1 panel
[12/6/2020, 9:01:04 PM] [ElkM1] Timout occured before Text Description (sd) was received.

Config:

{
    "platform": "ElkM1",
    "name": "ElkM1",
    "elkAddress": "x.x.x.x",
    "elkPort": "2101",
    "area": "1",
    "keypadCode": "XXXX",
    "zoneTypes": {
        "15": "contact",
        "16": "contact",
        "17": "contact",
        "18": "motion",
        "25": "contact",
        "26": "contact",
        "27": "contact",
        "28": "contact",
        "29": "contact",
        "30": "contact",
        "31": "contact",
        "37": "contact",
        "38": "contact",
        "39": "contact",
        "40": "contact",
        "41": "contact",
        "42": "contact",
        "43": "contact",
        "194": "contact"
    }
}

- Elk board is on latest fw, on the same subnet as the Homebridge server, and the homebridge server can ping the panel.

- The windows M1ToGo app can successfully connect to the panel on the insecure port and have full control.

- There are text descriptions on all zones

- There are some zones on the panel not included in Homebridge, such. as a temperature zone.

Do you have any thoughts?

Thanks for all of the amazing work you did for this plugin!

**Comment by paulw11** [comment] 2020-12-07 04:24
This appears to be a duplicate of #10.

The problem in that instance is inside the elkmon package that this package depends upon.  Can you run home bridge in DEBUG mode and share the debug log?  That might provide more information

**Comment by 2765827892** [comment] 2020-12-08 01:50
Thanks for the quick response!

So, I actually enabled debugging and copy and pasted all of the relevant logs when I posted.  Is there someplace else you want me to look? I can confirm that there are more items when debugging is enabled. 

Thanks again!

**Comment by paulw11** [comment] 2020-12-08 07:51
I can see from the log that it looks like it had a problem getting the zone descriptions.  I have updated the plugin with a bit more debug logging.  Can you try it and provide the [elkm1] logs?

**Closed** 2021-03-22 00:23 UTC

**Comment by paulw11** [comment] 2021-03-23 19:59
Root cause determined in #20
